Individual
const float Individual.MUTATION_MULT
const int Individual.LIFETIME_FUNC
const int Individual.SURVIVAL_FUNC
const int Individual.ACCURACY_FUNC
const int Individual.NB_ON_TARGET_FUNC
const int Individual.ACCURATE_LONG_LIFE_FUNC
DodgeAI Individual.dodgeAI
Mover Individual.mover
WeaponController Individual.weaponController
GameObject Individual.enemyShip
float Individual.speed
float Individual.dodge
float Individual.minDodgeTime
float Individual.maxDodgeTime
float Individual.minDodgeWait
float Individual.maxDodgeWait
float Individual.minFireRate
float Individual.maxFireRate
float Individual.fitness
int Individual.minDodgeBound
int Individual.maxDodgeBound
float Individual.minDodgeTimeBound
float Individual.maxDodgeTimeBound
float Individual.minDodgeWaitBound
float Individual.maxDodgeWaitBound
float Individual.minSpeedBound
float Individual.maxSpeedBound
float Individual.minFireRateBound
float Individual.maxFireRateBound
float Individual.creationTime
float Individual.lifetime
float Individual.accuracy
int Individual.nbShotsOnTarget
bool Individual.survived
Individual Individual.item
int Individual.MinDodgeBound
Accessor and Mutator for minDodgeBound.
Referenced by SetRandomAttributes.
int Individual.MaxDodgeBound
Accessor and Mutator for maxDodgeBound.
Referenced by SetRandomAttributes.
float Individual.MinDodgeTimeBound
Accessor and Mutator for minDodgeTimeBound.
Referenced by SetRandomAttributes.
float Individual.MaxDodgeTimeBound
Accessor and Mutator for maxDodgeTimeBound.
Referenced by SetRandomAttributes.
float Individual.MinDodgeWaitBound
Accessor and Mutator for minDodgeWaitBound.
Referenced by SetRandomAttributes.
float Individual.MaxDodgeWaitBound
Accessor and Mutator for maxDodgeWaitBound.
Referenced by SetRandomAttributes.
float Individual.MinSpeedBound
Accessor and Mutator for minSpeedBound.
Referenced by SetRandomAttributes.
float Individual.MaxSpeedBound
Accessor and Mutator for maxSpeedBound.
Referenced by SetRandomAttributes.
float Individual.MinFireRateBound
Accessor and Mutator for minFireRateBound.
Referenced by SetRandomAttributes.
float Individual.MaxFireRateBound
Accessor and Mutator for maxFireRateBound.
Referenced by SetRandomAttributes.
float Individual.Speed
Accessor and Mutator for speed.
Referenced by EvolutionController.DisplayMostPowerfulEnemy, CopyGenes, CrossoverAttributes, SetSpeed.
float Individual.Dodge
Accessor and Mutator for dodge.
Referenced by EvolutionController.DisplayMostPowerfulEnemy, CopyGenes, CrossoverAttributes, SetDodge.
float Individual.MinDodgeTime
Accessor and Mutator for minDodgeTime.
Referenced by CopyGenes, CrossoverAttributes, SetDodgeTimeRange.
float Individual.MaxDodgeTime
Accessor and Mutator for maxDodgeTime.
Referenced by CopyGenes, CrossoverAttributes, SetDodgeTimeRange.
float Individual.MinDodgeWait
Accessor and Mutator for minDodgeWait.
Referenced by EvolutionController.DisplayMostPowerfulEnemy, CopyGenes, CrossoverAttributes, SetDodgeWaitRange.
float Individual.MaxDodgeWait
Accessor and Mutator for minDodgeWait.
Referenced by EvolutionController.DisplayMostPowerfulEnemy, CopyGenes, CrossoverAttributes, SetDodgeWaitRange.
float Individual.MinFireRate
Accessor and Mutator for minFireRate.
Referenced by EvolutionController.DisplayMostPowerfulEnemy, CopyGenes, CrossoverAttributes, SetFireRateRange.
float Individual.MaxFireRate
Accessor and Mutator for maxFireRate.
Referenced by EvolutionController.DisplayMostPowerfulEnemy, CopyGenes, CrossoverAttributes, SetFireRateRange.
float Individual.Fitness
Accessor and Mutator for fitness.
Referenced by CalculateFitness.
GameObject Individual.EnemyShip
Accessor and Mutator for enemyShip.
Referenced by Individual, SetRandomAttributes.
float Individual.Lifetime
Accessor and Mutator for lifetime.
Referenced by EvolutionController.DisplayMostPowerfulEnemy, Complete, LifetimeFunc, AccurateLongLifeFunc.
bool Individual.Survived
Accessor and Mutator for survived.
Referenced by EvolutionController.DisplayMostPowerfulEnemy, Complete, SurvivalFunc.
Individual.Individual(GameObject enemyShipObject)
Create an individual from an enemy ship prefab.
enemyShipObject The enemy ship to create an individual from.
References EnemyShip, SetRandomAttributes.
Individual.Individual(Individual copy)
Create an individual given another individual
copy The individual to copy.
References CopyGenes.
void Individual.CopyGenes(Individual src)
Copy genes from an individual
src The individual to copy genes from.
References Speed, Dodge, MinDodgeTime, MaxDodgeTime, MinDodgeWait, MaxDodgeWait, MinFireRate, MaxFireRate.
Referenced by Individual.
void Individual.Complete(bool survivedWave)
Mark that the individual has completed the wave.
survivedWave Whether the the individual survived or not.
References Lifetime, Survived.
void Individual.CrossoverAttributes(Individual father, Individual mother)
Perform crossover between two parents, keeping attributes within set bounds.
father The first parent. mother The second parent.
References SetSpeed, Speed, SetDodge, Dodge, SetDodgeTimeRange, MinDodgeTime, MaxDodgeTime, SetDodgeWaitRange, MinDodgeWait, MaxDodgeWait, SetFireRateRange, MinFireRate, MaxFireRate.
void Individual.MutateAttributes()
Mutate the attributes of an individual
References RandomVerticalSpeed, RandomDodge, RandomDodgeTime, RandomDodgeWait, RandomFireRate.
float Individual.LifetimeFunc()
Calculate fitness based on lifetime.
The calculated fitness score.
References Lifetime.
Referenced by CalculateFitness.
float Individual.SurvivalFunc()
Calculate fitness based on survival.
The calculated fitness score.
References Survived.
Referenced by CalculateFitness.
float Individual.AccuracyFunc()
Calculate fitness based on accuracy.
The calculated fitness score.
References GetAccuracy.
Referenced by CalculateFitness.
float Individual.NbOnTargetFunc()
Calculate fitness based on the number of shots on target.
The calculated fitness score.
References GetNbShotsOnTarget.
Referenced by CalculateFitness.
float Individual.GetAccuracy()
Get the accuracy of the individual.
The accuracy value of the individual.
References WeaponController.GetAccuracy.
Referenced by EvolutionController.DisplayMostPowerfulEnemy, AccuracyFunc, AccurateLongLifeFunc.
float Individual.GetNbShotsOnTarget()
Get the number of shots on target the individual made.
The number of shots on target of the individual.
References WeaponController.GetNbShotsOnTarget.
Referenced by EvolutionController.DisplayMostPowerfulEnemy, NbOnTargetFunc.
float Individual.AccurateLongLifeFunc()
Calculate fitness based on lifetime and accuracy.
The calculated fitness score.
References GetAccuracy, Lifetime.
Referenced by CalculateFitness.
float Individual.CalculateFitness(int selectedFunction)
Calculate the fitness of the individual.
selectedFunction The index of the selected fitness function. The calculated fitness score.
References Fitness, LifetimeFunc, SurvivalFunc, AccuracyFunc, NbOnTargetFunc, AccurateLongLifeFunc.
void Individual.SetRandomAttributes()
Set attributes randomly.
References EnemyShip, RandomDodge, MinDodgeBound, MaxDodgeBound, RandomDodgeTime, MinDodgeTimeBound, MaxDodgeTimeBound, RandomDodgeWait, MinDodgeWaitBound, MaxDodgeWaitBound, RandomVerticalSpeed, MinSpeedBound, MaxSpeedBound, RandomFireRate, MinFireRateBound, MaxFireRateBound.
Referenced by Individual.
void Individual.RandomDodge(float minDodge, float maxDodge)
Set dodge randomly within a range.
minDodge The minimum dodge value. maxDodge The maximum dodge value.
References SetDodge.
Referenced by MutateAttributes, SetRandomAttributes.
void Individual.RandomDodgeTime(float minDodgeTime, float maxDodgeTime)
Set dodge time randomly within a range.
minDodgeTime The minimum dodge time. maxDodgeTime The maximum dodge time.
References SetDodgeTimeRange.
Referenced by MutateAttributes, SetRandomAttributes.
void Individual.RandomDodgeWait(float minDodgeWait, float maxDodgeWait)
Set dodge wait randomly within a range.
minDodgeWait The minimum dodge wait. maxDodgeWait The maximum dodge wait.
References SetDodgeWaitRange.
Referenced by MutateAttributes, SetRandomAttributes.
void Individual.RandomVerticalSpeed(float minSpeed, float maxSpeed)
Set speed randomly within a range.
minSpeed The minimum speed value. maxSpeed The maximum speed value.
References SetSpeed.
Referenced by MutateAttributes, SetRandomAttributes.
void Individual.RandomFireRate(float minFireRate, float maxFireRate)
Set fire rate randomly within a range.
minFireRate The minimum fire rate value. maxFireRate The maximum fire rate value.
References SetFireRateRange.
Referenced by MutateAttributes, SetRandomAttributes.
void Individual.SetSpeed(float s)
Set a new speed value.
s The new speed value.
References Mover.SetSpeed, Speed.
Referenced by CrossoverAttributes, RandomVerticalSpeed.
void Individual.SetDodge(float d)
Set a new dodge value.
d The new dodge value.
References Dodge.
Referenced by CrossoverAttributes, RandomDodge.
void Individual.SetDodgeTimeRange(float min, float max)
Set a new dodge time range.
min The new minimum dodge time. max The new maximum dodge time.
References MinDodgeTime, MaxDodgeTime.
Referenced by CrossoverAttributes, RandomDodgeTime.
void Individual.SetDodgeWaitRange(float min, float max)
Set a new dodge wait range.
min The new minimum dodge wait. max The new maximum dodge wait.
References MinDodgeWait, MaxDodgeWait.
Referenced by CrossoverAttributes, RandomDodgeWait.
void Individual.SetFireRateRange(float min, float max)
Set a new fire rate range.
min The new minimum fire rate. max The new maximum fire rate.
References MinFireRate, MaxFireRate.
Referenced by CrossoverAttributes, RandomFireRate.
float Individual.CrossoverPoint(float x, float y)
Calculate the crossover point between two values.
x The first value. y The second value. The calculated crossover point between x and y.